sudo: true
language: node_js
branches:
  only:
  - master
install: # needed to run build/deployment scripts
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version
  - npm install --only=production
before_script:
- make ensure-dependencies
script:
- make brand
- make package
- make qa
matrix:
  include:
  - env: SERVICE=movies-api
    services:
    - docker